name: dslink_dart_test
version: 0.0.1
description: A simple console application.
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dependencies:
  test: '>=0.12.13+1 <0.13.0'
  dslink:
    git: git@github.com:IOT-DSA/sdk-dslink-dart.git
